/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaapplication2.ferramentas.Anuidade;
import javaapplication2.ferramentas.Tabua;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Avery
 */
public class AnuidadeTemporariaJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AnuidadeVitaliciaJFrame
     */
    public AnuidadeTemporariaJFrame() {
        initComponents();
        
        if(!new File("tabua_atuarial.csv").exists())
        {
            JOptionPane.showMessageDialog(
                                        null, 
                                        "IMPORTE A TÁBUA PRIMEIRO (FERRAMENTAS > IMPOTAÇÃO DA TÁBUA)", 
                                        "ATENÇÃO", 
                                        JOptionPane.WARNING_MESSAGE);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        anuidade_temporaria_idade = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        anuidade_temporaria_diferimento = new javax.swing.JTextField();
        anuidade_temporaria_postecipada = new javax.swing.JCheckBox();
        anuidade_temporaria_taxa_juros = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        anuidade_temporaria_resultado = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        anuidade_temporaria_duracao = new javax.swing.JTextField();
        anuidade_temporaria_beneficio = new javax.swing.JTextField();
        anuidade_temporaria_calcular = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Anuidade temporária");

        jLabel1.setText("Idade");

        anuidade_temporaria_idade.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        anuidade_temporaria_idade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        anuidade_temporaria_idade.setName(""); // NOI18N
        anuidade_temporaria_idade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inteiro(evt);
            }
        });

        jLabel2.setText("Benefício");

        jLabel3.setText("Taxa de juros (%)");

        jLabel4.setText("Diferimento");

        anuidade_temporaria_diferimento.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        anuidade_temporaria_diferimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        anuidade_temporaria_diferimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                diferimentoHandler(evt);
            }
        });

        anuidade_temporaria_postecipada.setText("Postecipada?");

        anuidade_temporaria_taxa_juros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            anuidade_temporaria_taxa_juros.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("0.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        anuidade_temporaria_taxa_juros.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        anuidade_temporaria_taxa_juros.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                taxaJurosFocusLost(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        anuidade_temporaria_resultado.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        anuidade_temporaria_resultado.setForeground(new java.awt.Color(255, 255, 255));
        anuidade_temporaria_resultado.setText("0,00");
        anuidade_temporaria_resultado.setToolTipText("");
        anuidade_temporaria_resultado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(anuidade_temporaria_resultado, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(anuidade_temporaria_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jLabel5.setText("Duração");

        anuidade_temporaria_duracao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        anuidade_temporaria_duracao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        anuidade_temporaria_beneficio.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        anuidade_temporaria_beneficio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anuidade_temporaria_beneficio)
                    .addComponent(anuidade_temporaria_diferimento)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(anuidade_temporaria_taxa_juros, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jLabel4))
                                .addComponent(anuidade_temporaria_idade)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anuidade_temporaria_postecipada)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(anuidade_temporaria_duracao, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(anuidade_temporaria_idade, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anuidade_temporaria_taxa_juros, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(anuidade_temporaria_beneficio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anuidade_temporaria_diferimento, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anuidade_temporaria_duracao, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(anuidade_temporaria_postecipada)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        anuidade_temporaria_calcular.setText("Calcular");
        anuidade_temporaria_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anuidade_temporaria_calcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 573, Short.MAX_VALUE)
                        .addComponent(anuidade_temporaria_calcular)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(anuidade_temporaria_calcular)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Apenas números inteiros
    */
    private void inteiro(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inteiro
        char digitou = evt.getKeyChar();
        if(!(Character.isDigit(digitou))){
            evt.consume();
        }
    }//GEN-LAST:event_inteiro

    private void diferimentoHandler(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diferimentoHandler
        char digitou = evt.getKeyChar();
        if(!(Character.isDigit(digitou))){
            evt.consume();
        }
    }//GEN-LAST:event_diferimentoHandler

    private void taxaJurosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_taxaJurosFocusLost
    
        anuidade_temporaria_taxa_juros.setFocusLostBehavior(JFormattedTextField.PERSIST);
        try{
            System.out.println(anuidade_temporaria_taxa_juros.getText());
            float inputNum = Float.parseFloat(anuidade_temporaria_taxa_juros.getText());
            if(inputNum<0 || inputNum>1) {
                JOptionPane.showMessageDialog(
                                        null, 
                                        "FORNEÇA UM VALOR ENTRE 0 (ZERO) E 1 PARA A TAXA DE JUROS", 
                                        "ATENÇÃO", 
                                        JOptionPane.WARNING_MESSAGE);
            }
        }catch(java.lang.NumberFormatException e){
            //anuidade_vitalicia_taxa_juros.setText("");
            anuidade_temporaria_taxa_juros.requestFocus();
        }
        
    }//GEN-LAST:event_taxaJurosFocusLost

    private void anuidade_temporaria_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anuidade_temporaria_calcularActionPerformed
       
        try{
            boolean postecipada;
            if( anuidade_temporaria_postecipada.isSelected() ){
                postecipada = true;
            }else{
                postecipada = false;
            }

            int soma = Integer.parseInt(anuidade_temporaria_idade.getText()) + Integer.parseInt(anuidade_temporaria_diferimento.getText());
            
            Tabua.carregaTabua();
            
            if(soma > Tabua.qx.length)
            {
                JOptionPane.showMessageDialog(
                                        null, 
                                        "A SOMA IDADE + DIFERIMENTO DEVE SER INFERIOR AO OMEGA DA TÁBUA = ".concat(String.valueOf(Tabua.qx.length)), 
                                        "ATENÇÃO", 
                                        JOptionPane.WARNING_MESSAGE);
            }else{
                
                double res = Anuidade.getAnuidadeTemporaria(
                    Integer.parseInt(anuidade_temporaria_idade.getText()), 
                    Integer.parseInt(anuidade_temporaria_duracao.getText()),
                    Double.valueOf(anuidade_temporaria_beneficio.getText()), 
                    postecipada, 
                    Double.valueOf(anuidade_temporaria_taxa_juros.getText()),
                    Integer.parseInt(anuidade_temporaria_diferimento.getText()));

                anuidade_temporaria_resultado.setText(String.valueOf(res));
                
            }
        
        }
        catch(java.lang.NumberFormatException e){
            JOptionPane.showMessageDialog(
                                        null, 
                                        "VERIFIQUE SE VOCÊ PREENCHEU TODOS OS CAMPOS CORRETAMENTE!", 
                                        "ATENÇÃO", 
                                        JOptionPane.ERROR_MESSAGE);
        }
        catch(Error e){
            JOptionPane.showMessageDialog(
                                        null, 
                                        "VERIFIQUE SE VOCÊ PREENCHEU TODOS OS CAMPOS CORRETAMENTE!", 
                                        "ATENÇÃO", 
                                        JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_anuidade_temporaria_calcularActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnuidadeTemporariaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnuidadeTemporariaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnuidadeTemporariaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnuidadeTemporariaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnuidadeTemporariaJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anuidade_temporaria_beneficio;
    private javax.swing.JToggleButton anuidade_temporaria_calcular;
    private javax.swing.JTextField anuidade_temporaria_diferimento;
    private javax.swing.JTextField anuidade_temporaria_duracao;
    private javax.swing.JTextField anuidade_temporaria_idade;
    private javax.swing.JCheckBox anuidade_temporaria_postecipada;
    private javax.swing.JLabel anuidade_temporaria_resultado;
    private javax.swing.JFormattedTextField anuidade_temporaria_taxa_juros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
