/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

import com.opencsv.CSVReader;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaapplication2.ferramentas.Tabua;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Avery
 */
public class MainWindowJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainWindowJFrame() {
        initComponents();
        
        File file = new File("tabua_atuarial.csv");
            
        if(!file.exists())
        {
            JOptionPane.showMessageDialog(
                null, 
                "VOCÊ PRECISA IMPORTAR UMA TÁBUA PRIMEIRO (FERRAMENTAS > IMPOTAÇÃO DA TÁBUA)", 
                "ATENÇÃO", 
                JOptionPane.WARNING_MESSAGE);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        menuSeguroVitalicio = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuSeguroTemporario = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuSeguroDotal = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora Atuarial");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arte3.png"))); // NOI18N

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("FERRAMENTAS");
        jMenu1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("ANUIDADE");
        jMenu2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem1.setText("VITALÍCIA");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem2.setText("TEMPORÁRIA");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenu1.add(jMenu2);
        jMenu1.add(jSeparator1);

        jMenu3.setBackground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("SEGURO");
        jMenu3.setActionCommand("seguro");
        jMenu3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        menuSeguroVitalicio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        menuSeguroVitalicio.setText("VITALÍCIO");
        menuSeguroVitalicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSeguroVitalicioActionPerformed(evt);
            }
        });
        jMenu3.add(menuSeguroVitalicio);
        jMenu3.add(jSeparator3);

        menuSeguroTemporario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        menuSeguroTemporario.setText("TEMPORÁRIO");
        menuSeguroTemporario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSeguroTemporarioActionPerformed(evt);
            }
        });
        jMenu3.add(menuSeguroTemporario);
        jMenu3.add(jSeparator4);

        menuSeguroDotal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        menuSeguroDotal.setText("DOTAL");
        menuSeguroDotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSeguroDotalActionPerformed(evt);
            }
        });
        jMenu3.add(menuSeguroDotal);

        jMenu1.add(jMenu3);
        jMenu1.add(jSeparator2);

        jMenuItem6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem6.setText("IMPORTAÇÃO DA TÁBUA");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem3.setText("SOBRE");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        

        AnuidadeVitaliciaJFrame av = new AnuidadeVitaliciaJFrame();

        // Centraliza a janela
        av.setLocation(
            // Centraliza na horizontal
            (Toolkit.getDefaultToolkit().getScreenSize().width/2) - (av.getSize().width/2),
            // Centraliz na vertical
            (Toolkit.getDefaultToolkit().getScreenSize().height/2) - (av.getSize().height/2));

        // Exibe a janela (Este método me parece que está obsoleto e eu não sei ainda qual é o substituto. Mas funciona)
        av.setResizable(false);
        av.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        ImportarTabuaJFrame it = new ImportarTabuaJFrame();        
        
        // Centraliza a janela
        it.setLocation(
                // Centraliza na horizontal
                (Toolkit.getDefaultToolkit().getScreenSize().width/2) - (it.getSize().width/2),
                // Centraliz na vertical
                (Toolkit.getDefaultToolkit().getScreenSize().height/2) - (it.getSize().height/2));

        // Exibe a janela (Este método me parece que está obsoleto e eu não sei ainda qual é o substituto. Mas funciona)
        it.setResizable(false);
        it.show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        AnuidadeTemporariaJFrame at = new AnuidadeTemporariaJFrame();        
        
        // Centraliza a janela
        at.setLocation(
                // Centraliza na horizontal
                (Toolkit.getDefaultToolkit().getScreenSize().width/2) - (at.getSize().width/2),
                // Centraliz na vertical
                (Toolkit.getDefaultToolkit().getScreenSize().height/2) - (at.getSize().height/2));

        // Exibe a janela (Este método me parece que está obsoleto e eu não sei ainda qual é o substituto. Mas funciona)
        at.setResizable(false);
        at.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuSeguroVitalicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSeguroVitalicioActionPerformed
        SeguroVitalicioJFrame sv = new SeguroVitalicioJFrame();        
        sv.setLocation(
                (Toolkit.getDefaultToolkit().getScreenSize().width/2) - (sv.getSize().width/2),
                (Toolkit.getDefaultToolkit().getScreenSize().height/2) - (sv.getSize().height/2));
        sv.setResizable(false);
        sv.show();
    }//GEN-LAST:event_menuSeguroVitalicioActionPerformed

    private void menuSeguroTemporarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSeguroTemporarioActionPerformed
        SeguroTemporarioJFrame st = new SeguroTemporarioJFrame();        
        st.setLocation(
                (Toolkit.getDefaultToolkit().getScreenSize().width/2) - (st.getSize().width/2),
                (Toolkit.getDefaultToolkit().getScreenSize().height/2) - (st.getSize().height/2));
        st.setResizable(false);
        st.show();
    }//GEN-LAST:event_menuSeguroTemporarioActionPerformed

    private void menuSeguroDotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSeguroDotalActionPerformed
        SeguroDotalJFrame sd = new SeguroDotalJFrame();        
        sd.setLocation(
                (Toolkit.getDefaultToolkit().getScreenSize().width/2) - (sd.getSize().width/2),
                (Toolkit.getDefaultToolkit().getScreenSize().height/2) - (sd.getSize().height/2));
        sd.setResizable(false);
        sd.show();
    }//GEN-LAST:event_menuSeguroDotalActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Sobre sob = new Sobre();
        sob.setLocation(
                (Toolkit.getDefaultToolkit().getScreenSize().width/2) - (sob.getSize().width/2),
                (Toolkit.getDefaultToolkit().getScreenSize().height/2) - (sob.getSize().height/2));
        sob.setResizable(false);
        sob.show();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindowJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindowJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindowJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindowJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
                new MainWindowJFrame().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuItem menuSeguroDotal;
    private javax.swing.JMenuItem menuSeguroTemporario;
    private javax.swing.JMenuItem menuSeguroVitalicio;
    // End of variables declaration//GEN-END:variables
}
